PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE ancestries (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    source VARCHAR(20) NOT NULL DEFAULT 'core',
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(name, source)
);
INSERT INTO ancestries VALUES(1,'Human','core','Humans in most settings get one free Edge of their choice. This option reflects their versatility and adaptability compared to most other ancestries. For more variety, the GM might give humans abilities based on culture.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(2,'Dwarf','core','Dwarves are short but stout, hardy people who come from massive caverns or high mountains. They are a proud, warlike people, usually made so by frequent contact with hostile creatures such as orcs and goblins. Dwarves usually live upwards of 200 years.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(3,'Elf','core','Elves are tall, thin souls with pointed ears and deep-set eyes of various colors. Whether they hail from the deep forests or hidden valleys, they are all born more graceful than humans, though somewhat slighter. Most elves live upwards of 300 years.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(4,'Aquarian','core','From the crushing ocean depths come aquatic folk. They are thick and sturdy beneath the waves but often vulnerable in the dry air or searing heat of the surface.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(5,'Avion','core','Avions are humanoids with wings. They tend to be very slight of build owing to their hollow bones. Some are feathered while others are leathery or even scaled.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(6,'Android','core','Androids are semi-organic beings created by advanced technology. The example here mimics humans in most ways and can generally pass for them when desired. Their advanced neural network gives them artificial intelligence complete with individual personalities, quirks, and emotions.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(7,'Rakashan','core','Rakashans are humanoid felines. Some have the bright colors of tigers, the speckled hides of leopards, or the exotic look of Siamese cats. All have sharp claws and teeth, and a cruel nature when it comes to dealing with their prey. They can be found in their own remote cities or as fringe elements of normal society.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO ancestries VALUES(8,'Aquarian','fantasy_companion','From the crushing ocean depths come these aquatic folk. They take a variety of forms, from fish-headed deep dwellers to humanoids with barely visible gills on their sides or necks. The depths make them thick and sturdy but they suffer greatly in the dry air or searing heat of the surface.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(9,'Avion','fantasy_companion','Avions are humanoids with wings, often from high forest or mountain regions. Avions may be crow-like birdfolk, hawk-like raptors, or have the leathery wings of bats, but all tend to be very slight of build due to their hollow bones.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(10,'Celestial','fantasy_companion','In many worlds, the gods and goddesses take an active interest in the affairs of mortals, sending angels into the mortal realm to serve as their representatives. Celestials have many forms, but their most noteworthy trait is a pair of white, feathery wings sprouting from their back.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(11,'Centaur','fantasy_companion','Centaurs have the lower body of a horse and the upper body of a man. Most stand as tall as humans, though larger lines exist. Centaurs encompasses all horse-human hybrids, including those descended from exotic species such as pegasi or zebras.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(12,'Dragonfolk','fantasy_companion','The humanoid dragonfolk hail from scorching deserts, volcanic caves, or steaming jungles. Some say their temperaments are almost as fiery as the lands they call home. They are similar to other lizard-like humanoids but have the ability to breathe fire like the great dragons themselves.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(13,'Dwarf','fantasy_companion','Dwarves are short, stout, hardy people who come from massive caverns deep within the earth or high mountain strongholds. They are typically a proud, warlike race due to frequent contact with hostile races such as orcs and goblins. Dwarves usually live upwards of 200 years. In most fantasy campaigns, they are known for their love of ale, knowledge of stoneworking, and impressive beards.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(14,'Elemental Scion','fantasy_companion','Elemental scions are somehow connected by birth to one of the four elements: earth, fire, water, or air. The type here looks mostly human, but may have telltale signs of their heritage. Air scions have white hair that continuously stirs as if blown in a phantom wind. Earth scions have gravelly voices, brawny bodies, and a ruddy cast to their skin. Fire scions have a shock of bright orange or yellow hair, sibilant voices, and red pupils. Water scions have a bluish tint to their skin and hair, and speak with silvery voices.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(15,'Elf','fantasy_companion','Elves are a tall, thin people with pointed ears and deep-set eyes of various colors. Whether they hail from the deep forests or hidden valleys, they are a graceful, spiritual people who may live several centuries. Most have fair skin with hair of various hues, including shades of silver, blue, and gold.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(16,'Fairy','fantasy_companion','Fairies are an integral part of high fantasy. They are small, often-impetuous winged creatures who serve a fairy queen, king, or court. Danger is always close at hand in a world of much larger creatures, so they must choose their battles carefully, perhaps relying on traps, tricks, or alliances with larger beings to defeat their foes.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(17,'Gnome','fantasy_companion','Gnomes are small humanoids who live in deep forests, mountain caves, or other dark and isolated places. They are often mistaken for half-folk, but the type here is better proportioned and have less hair.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(18,'Goblin','fantasy_companion','Few argue that goblins are quarrelsome beings. Most serve orcs, ogres, or other larger humanoids, acting as scouts, weapon carriers, or even food. Sometimes tribes are brought together by circumstance, opportunity, or cunning leaders, but most have short and brutal lives thanks to their larger cousins, bloodthirsty adventurers, or hungry predators.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(19,'Golem','fantasy_companion','Golems are generally mindless automatons created by a sorcerer or inventor to protect their lairs. But some are either gifted with sentience or come into it through arcane accidents, powerful spells, blessings by benevolent deities, or other unorthodox means.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(20,'Graveborn','fantasy_companion','The mysterious and rare graveborn - sometimes called "dhampyres" - are the offspring of a living parent and a vampire. Most do not survive into adulthood, succumbing to ill health, the unforgiving sun, or superstitious villagers, but those who do can be very powerful indeed. Graveborn are not undead but have a sickly gray complexion, stringy hair, and dark eyes. Their frail appearance belies abnormal strength, however. They have an innate connection to the dead and cause other living creatures around them - especially animals - to feel uneasy.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(21,'Half-Elf','fantasy_companion','Half-elves gain the elven grace or the adaptability of their human parent. Most are well-adjusted, but some are shunned by one side of the family or the other and grow resentful. Others may even be mistreated. Their lifespans are closer to their human parent than those of their elven kin, living only to about 100 years.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(22,'Half-Folk','fantasy_companion','Half-folk are short, hairy, and typically amiable people. Their cheerful optimism (or wily cunning) gives them a "never say die" attitude that makes them more than a match for those who would trouble them. Most half-folk enjoy life''s little luxuries - good food, strong drink, and lively music. Few are adventurous, preferring to stay in close-knit communities far from trouble.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(23,'Half-Giant','fantasy_companion','Tribes of these outcasts can be found in distant hills, yawning chasms, and towering mountains. They are strong, unstoppable forces well-suited to battling their way through the most savage environments.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(24,'Half-Orc','fantasy_companion','Half-orcs are the offspring of an orc and a human or another half-orc. They are usually accepted by orcish communities but shunned by most other races, including humans, elves, and dwarves. Some half-orcs choose to join the "civilized" races, turning their backs on their barbaric roots. They vary greatly in appearance. Some are large and powerful, like orcs, while others can pass for human without close examination.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(25,'Human','fantasy_companion','Humans are adaptable and ubiquitous in most fantasy settings, with traits common to their home culture rather than their species.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(26,'Infernal','fantasy_companion','Infernals have demonic or devilish blood in their line. They are not inherently evil, but most are mischievous, either by nature or perhaps because they are expected to be by others. They come in many shapes and sizes, but all have some sort of telltale physical trait, such as a tail, horns, or serpent-like eyes.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(27,'Insectoid','fantasy_companion','Insectoids or insectfolk come in many varieties. The template here features an ant-like being of roughly human size. Culturally, most insectoids come from highly-organized societies built around roles assigned at birth and tend to be obedient to a fault.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(28,'Minotaur','fantasy_companion','Minotaurs have a human body and the head and musculature of a bull. They may be mythological creatures, created by deities as a form of punishment, or simply a humanoid species with their own culture and customs. Regardless of origin, minotaurs are known for their physical strength, ill tempers, and wicked horns. They are fearsome in one-on-one combat.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(29,'Mouseling','fantasy_companion','These tiny creatures resemble ordinary mice except for being bipedal and intelligent. Perhaps they were normal mice given sentience by a magical mishap. Or maybe they have always existed, hiding in the shadows of the larger races.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(30,'Ogre','fantasy_companion','The proud and vicious ogres live in tribes most others see as savage and cruel. They pride themselves on gluttony and great feats of bravery or cunning. Whether they roam as nomads, rule a vital pass in the highest mountains, or lair in massive caverns near their "cousins" the orcs and goblins, their rowdy campfire feasts and the tales that come with them are legendary.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(31,'Orc','fantasy_companion','Orcs have a reputation for being savage, feral, brutish, and violent. This is not entirely unearned - marauding bands of orcs are terrors wherever they roam in most fantasy worlds. But where others see predation and cruelty, orcs see an uncomplicated struggle for survival. After all, in nature, the strongest outlast their enemies, and orcs see themselves no differently. Their social structure reflects this as tribes are ruled by the largest and toughest warriors, winning their thrones through honest but bloody combat rather than the guile and manipulation of more "civilized" societies.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(32,'Rakashan','fantasy_companion','Rakashans are humanoid felines. Some have the bright colors of tigers, the speckled hides of leopards, or the exotic look of Siamese cats. All have sharp claws and teeth, and a cruel nature when it comes to dealing with their prey. Rakashans can be found in their own remote and exotic cities or as fringe elements of normal society. They are often too clever and beautiful to be shunned, but too cunning to gain others'' complete trust.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(33,'Ratling','fantasy_companion','Natural-born survivors, ratlings are furry humanoids with hunched bodies, ratlike faces, and hairless tails. Opportunistic by necessity, their species has long been forced into sewers, tunnels, and slums by their many enemies. There they form loose packs, working together as long as it is expedient, but their social cohesion tends to fall apart in the face of perilous threats or undeniable opportunities.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(34,'Saurian','fantasy_companion','Lizard men typically come from steaming jungles, festering swamps, or deep deserts where they have unique civilizations unknown to other sentient races.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(35,'Serpentfolk','fantasy_companion','Slithering forth from great warrens or isolated nests are a variety of serpentine humanoids. Species vary greatly between the broader genus, representing constrictors and vipers of various types, but share the same humanoid physiology and serpent-like heads.','2026-01-03 21:24:41','2026-01-03 21:24:41');
INSERT INTO ancestries VALUES(36,'Shapeshifter','fantasy_companion','These peculiar and often mistrusted creatures have the ability to change their appearance to look like someone else. They are the ultimate social chameleons, moving stealthily through society. Some unscrupulous shapeshifters use this ability to become con artists, thieves, or even assassins, while others use it while entertaining to enhance their performance. Their "true" form is disturbing to behold - a largely featureless humanoid with gray skin and pupilless eyes.','2026-01-03 21:24:41','2026-01-03 21:24:41');
COMMIT;
