PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE arcane_backgrounds (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL UNIQUE,
    arcane_skill_id INTEGER NOT NULL,
    starting_powers INTEGER NOT NULL,
    starting_power_points INTEGER NOT NULL,
    has_power_list BOOLEAN NOT NULL DEFAULT 0, -- FC arcane backgrounds have limited power lists
    source VARCHAR(20) NOT NULL DEFAULT 'core',
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (arcane_skill_id) REFERENCES skills(id)
);
INSERT INTO arcane_backgrounds VALUES(1,'Gifted',13,1,15,0,'core','The character has innate abilities that don''t fit into the usual tropes of magic, miracles, or psionics. Their powers may be low-level super powers, divine gifts, or even alien abilities, and are often very unusual or unique for their setting.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO arcane_backgrounds VALUES(2,'Magic',28,3,10,0,'core','Magicians range from powerful wizards to vile cultists. They draw on raw supernatural energy to fuel their eldritch fires. This energy infuses the worlds in which they live, and is drawn forth with gestures, words of power, or ancient runes.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO arcane_backgrounds VALUES(3,'Miracles',11,3,10,0,'core','Those who invoke miracles draw their power from a divine presence of some sort, including gods, nature, or spirits. Their powers are usually invoked with a few words of prayer or by performing established rituals. Champions of their particular religions, they typically have Hindrances that pertain to their service.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO arcane_backgrounds VALUES(4,'Psionics',22,3,10,0,'core','Psionicists tap into their own mental energy to manipulate matter, read minds, and far more. Some are agents in the employ of a vast government agency, while others are often on the run from them! Some may have years of training or they might have developed their incredible powers in isolation.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO arcane_backgrounds VALUES(5,'Weird Science',32,2,15,0,'core','Weird scientists use strange and powerful inventions beyond the normal technological level of the setting. Such creations might be possible due to super fuels, alien discoveries, or the raw intellect of rare super-geniuses who push the boundaries of science. Their Trappings must always include the item they''re associated with, and they must have their devices at hand to activate their powers.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO arcane_backgrounds VALUES(6,'Wizard',28,6,15,1,'fantasy_companion','The classic spellcaster of any fantasy campaign is the wizard. She might be an apprentice fresh from a magical academy, an aged mage who learned her craft by trial and error, or someone gifted from birth with eldritch affinity. Wizards have the largest spell selection of all the Arcane Backgrounds, but no inherent special abilities, and no access to critical powers such as healing or relief.','2026-01-04 20:18:20','2026-01-04 20:18:20');
INSERT INTO arcane_backgrounds VALUES(7,'Alchemist',33,3,15,1,'fantasy_companion','Alchemists create potions, oils, elixirs, and other consumables imbued with magical abilities. Their concoctions are created "off-camera" and activated as needed. As long as the alchemist has access to her bag, she can create Alchemical Items.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(8,'Bard',20,3,10,1,'fantasy_companion','Bards weave magic through song, story, and performance. They inspire their allies, confound their enemies, and are the keepers of lore and legend. Their magic comes through artistic expression rather than arcane formulas or divine prayer.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(9,'Cleric',11,5,10,1,'fantasy_companion','Clerics draw their power from a divine presence, including gods, nature, spirits, or revered ancestors. They invoke miracles by reciting prayers or performing rituals in their deity''s interests. A cleric''s powers depend on the domain of their deity.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(10,'Diabolist',28,5,10,1,'fantasy_companion','Diabolists conjure demons, spirits, and other malevolent entities from the abyss. Their magic always smacks of corruption and deviltry. They aren''t necessarily evil—they may use the powers of darkness against those who dare leave its punishing environs.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(11,'Druid',11,5,10,1,'fantasy_companion','Druids protect the wilderness, serve as priests for local communities, or wander communing with nature. They use natural artifacts as components and are bound to protect the natural world.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(12,'Elementalist',28,5,10,1,'fantasy_companion','Elementalists call on the planes of earth, fire, water, and air for their powers. They must choose a primary element which determines their spell Trappings and affects their power based on element proximity.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(13,'Illusionist',28,5,10,1,'fantasy_companion','Illusionists are extremely limited in power selection but are masters of the versatile illusion spell. Some manipulate light, others conjure ethereal phantasms, and some trick the observer''s mind.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(14,'Necromancer',28,5,10,1,'fantasy_companion','Necromancers blur the line between the worlds of the living and dead. Loathed by most, they relish the great power conferred by death''s dark energy.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(15,'Shaman',11,5,10,1,'fantasy_companion','Shamans are the spiritual backbone of those who live far from civilization. They commune with nature and spirits, worshiping and exploiting the natural world for the good of others.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(16,'Sorcerer',28,3,15,1,'fantasy_companion','Sorcerers are born with innate magical ability. Their powers manifest during puberty, and without proper training can be destructive and dangerous. Sorcerers have a wide selection of powers, and their magic comes more easily than to wizards, but they risk Corruption with every spell they cast.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(17,'Summoner',28,5,15,1,'fantasy_companion','Summoners specialize in summoning creatures from the natural world or other planes. Similar to diabolists but their servants are of animal intelligence and no more malevolent than any beast.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(18,'Tinkerer',23,2,15,1,'fantasy_companion','Tinkerers are highly specialized Weird Scientists who rely entirely on mechanical devices. They carry portable inventions for protection, expressed through gadgets like collapsible wings, goggles, and flintlock pistols.','2026-01-04 20:50:17','2026-01-04 20:50:17');
INSERT INTO arcane_backgrounds VALUES(19,'Warlock/Witch',28,3,10,1,'fantasy_companion','Warlocks (male) and witches (female) learn their craft from various sources: old grimoires, grandmother''s notes, and shadowy beings. Often feared, they are wary, protective, and secretive.','2026-01-04 20:50:17','2026-01-04 20:50:17');
COMMIT;
