PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE hindrances (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(50) NOT NULL,
    severity VARCHAR(10) NOT NULL CHECK (severity IN ('minor', 'major')),
    point_value INTEGER NOT NULL, -- 1 for minor, 2 for major
    companion_hindrance_id INTEGER, -- FK to the other variant, NULL if no companion
    source VARCHAR(20) NOT NULL DEFAULT 'core',
    description TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (companion_hindrance_id) REFERENCES hindrances(id)
);
INSERT INTO hindrances VALUES(1,'Arrogant','major',2,NULL,'core','Your hero doesn''t think he''s the best—he knows he is. Whether it''s swordsmanship, kung fu, or painting, few compare to his skills and he flaunts it every chance he gets. Winning isn''t enough for this champion. He wants to dominate his opponent and prove there''s no one better. He''s the kind of fighter who disarms an opponent in a duel just to pick the sword up and hand it back with a smirk. Arrogant individuals look for the greatest threat in battle, hacking their way through lesser minions only because they''re in the way.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(2,'Big Mouth','minor',1,NULL,'core','Loose lips sink ships, the saying goes. This hero''s mouth could drown an armada. The blabbermouth can''t keep a secret very well. He reveals plans and gives away things best kept among friends, usually at the worst possible times.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(3,'Bloodthirsty','major',2,NULL,'core','Your hero never takes prisoners unless under the direct supervision of a superior. His cold-blooded ruthlessness causes enemies to respond in kind, often costs vital information, creates constant enemies, and may get him in trouble with his superiors or the authorities, depending on the setting.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(4,'Cautious','minor',1,NULL,'core','This planner personifies restraint and carefulness. He never makes rash decisions and likes to plot things out in detail long before any action is taken.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(5,'Curious','major',2,NULL,'core','It killed the cat, and it might kill your warrior as well. Curious characters have to check out everything and always want to know what''s behind a potential mystery or secret.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(6,'Impulsive','major',2,NULL,'core','The daredevil almost always leaps before he looks. He rarely thinks things through before taking action.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(7,'Overconfident','major',2,NULL,'core','There''s nothing out there your hero can''t defeat. At least that''s what he thinks. He believes he can do most anything and never wants to retreat from a challenge. He''s not suicidal, but he certainly takes on more than common sense dictates.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(8,'Pacifist','minor',1,9,'core','Your hero absolutely despises violence. Minor pacifism means he only fights when given no other choice and never allows the killing of prisoners or other defenseless victims.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(9,'Pacifist','major',2,8,'core','Major Pacifists won''t fight living characters under any circumstances. They may defend themselves, but won''t do anything to permanently harm sapient, living creatures. They may use nonlethal methods (see page 98), but only in self-defense or the defense of others. Note that undeniably evil creatures, undead, demons, and the like are fair game even for Major Pacifists!','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(10,'Quirk','minor',1,NULL,'core','This individual has some minor foible that is usually humorous but can occasionally cause him real trouble. A swashbuckler may always try to slash his initials on his foes, a dwarf may brag constantly about his culture, or a snobby débutante might not eat, drink, or socialize with the lower class, for example.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(11,'Stubborn','minor',1,NULL,'core','Stubborn individuals always want their way and never admit they''re wrong. Even when it''s painfully obvious they''ve made a mistake they try to justify it with half-truths and rationalizations.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(12,'Bad Luck','major',2,NULL,'core','Your hero is a little less lucky than most. He gets one less Benny per game session than normal. A character cannot have both Bad Luck and the Luck Edge.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(13,'Enemy','minor',1,14,'core','Someone out there hates the character and wants him ruined, locked away, or dead. A Minor Enemy might be a lone gunslinger out for vengeance or a betrayed brotherhood that''s deadly but appears rarely.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(14,'Enemy','major',2,13,'core','A Major Enemy might represent powerful authorities, a band of outlaws, or a single very powerful and relentless rival. If the enemy is one day defeated, the GM should gradually work in a replacement, or the hero may buy off the Hindrance by sacrificing an Advance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(15,'Greedy','minor',1,16,'core','A miser measures worth in material possessions or wealth. If a Minor Hindrance, he argues bitterly for more than his fair share of any loot or reward the party might come across.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(16,'Greedy','major',2,15,'core','As a Major Hindrance, he fights over anything he considers unfair, and may even kill for it if he feels slighted or covets something he cannot have.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(17,'Obligation','minor',1,18,'core','Your hero has a responsibility she must attend to on a daily or regular basis. It could be a job, volunteer work, taking care of family or friends, etc. The Obligation consumes about 20 hours most weeks.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(18,'Obligation','major',2,17,'core','The Obligation consumes 40+ hours most weeks. Exactly what that entails should be discussed between the player and the Game Master.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(19,'Poverty','minor',1,NULL,'core','It''s said a fool and his money are soon parted. Your hero is one of them. He starts with half the usual money for your setting and just can''t seem to hang on to funds acquired after play begins. In general, the player halves his total funds every game week.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(20,'Secret','minor',1,21,'core','Your hero has a secret she keeps to protect herself or others. As a Minor Hindrance, the secret is troublesome but not life-threatening.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(21,'Secret','major',2,20,'core','The Major version would cause severe problems if discovered. If it ever becomes public knowledge, she should trade it for Enemy, Shamed, Wanted, or another appropriate Hindrance approved by the GM.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(22,'Shamed','minor',1,23,'core','Something haunts your adventurer. Maybe he made a vow he didn''t keep. Maybe he was defeated in an honorable fight and ordered the death of his foe anyway for some greater principle. Maybe he isn''t actually cowardly but once ran from a battle and left others to die. As a Minor Hindrance, the shameful circumstances aren''t generally known—it just haunts the hero. He might go out of his way, against all reason, not to repeat the mistake. Or he might give in to the same set of circumstances and hate himself for it.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(23,'Shamed','major',2,22,'core','As a Major Hindrance, his deed is well-known—or at least known among those he cares about. The other player characters should be told the tale as soon as possible (preferably at character creation). If not, it should be revealed by nonplayer characters at some point, and occasionally used against the hero.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(24,'Vengeful','minor',1,25,'core','Payback is…well…bad news for someone, and this adventurer is going to get it. As a Minor Hindrance she usually seeks vengeance legally. The method varies by situation. Some plot and scheme for months while others demand immediate results.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(25,'Vengeful','major',2,24,'core','Those with the Major version of this Hindrance don''t let anything prevent them from a reckoning. This doesn''t mean they immediately resort to violence, but their actions always escalate until total and complete satisfaction is achieved.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(26,'Vow','minor',1,27,'core','The character has sworn an oath to someone or something he believes in. The danger in fulfilling the Vow and how often it might occur determines the level of the Hindrance. A Minor Vow might be to serve an order with a broad mandate that rarely conflicts with the party''s goals.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(27,'Vow','major',2,26,'core','A Major Vow makes long-term and frequent demands on the servant''s time and results in great risks to his life.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(28,'Wanted','minor',1,29,'core','Your hero has committed some crime and will be arrested if discovered by the authorities. This assumes the setting actually has laws and police officers to enforce them. A hero with numerous unpaid parking tickets (in a game where he might have to drive occasionally) has a Minor Hindrance, as does someone wanted for more serious crimes away from the main campaign area.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(29,'Wanted','major',2,28,'core','Being accused of murder is a Major Hindrance in almost any setting if there''s someone around to seek justice (or vengeance).','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(30,'Young','minor',1,31,'core','The hero is 12–15 years old (in human years—adjust this for other ancestries). He has only 4 points to adjust his attributes instead of 5, and 10 skill points instead of 12. He may also have legal restrictions depending on the setting (can''t drive, own a firearm, and so on). On the plus side, youths have a fair amount of luck. They draw one extra Benny at the beginning of each game session (this stacks with other Edges such Luck or Great Luck). Most Young characters should also take the Small Hindrance, but it''s not mandatory.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(31,'Young','major',2,30,'core','As a Major Hindrance, the character is Very Young (8 to 11 years old). He has only 3 points for attributes and 10 for skills, and the Small Hindrance. Very Young heroes draw two extra Bennies at the start of each session.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(32,'Clueless','major',2,NULL,'core','Your hero doesn''t pay much attention to the world around him and can''t seem to find a haystack in a small pile of needles. He suffers a −1 penalty to Common Knowledge and Notice rolls.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(33,'Doubting Thomas','minor',1,NULL,'core','Some people don''t believe in the supernatural until they''re halfway down some creature''s gullet. Doubting Thomases are skeptics who try their best to rationalize supernatural events. They walk right into danger they don''t believe in and look for alternate explanations to every supernatural event. Even after being confronted with undeniable truth, the doubter''s mind eventually begins to doubt what he saw, rationalizes it away, or compartmentalizes the event as "one of a kind" while continuing to doubt the next mystery.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(34,'Illiterate','minor',1,NULL,'core','Your hero cannot read. He can sign his name and knows what a STOP sign says, but little else. He also doesn''t know much about math. He can probably do 2 + 2 = 4, but multiplication and the like are beyond him. Illiterate characters can''t read or write in any language, by the way, no matter how many they actually speak.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(35,'Timid','major',2,NULL,'core','Not everyone has ice water in their veins. Your hero is squeamish at the sight of blood and gore and terrified of coming to harm. He subtracts 2 from Fear checks and when resisting Intimidation.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(36,'Tongue-Tied','major',2,NULL,'core','Your adventurer flubs cool lines (or thinks of them afterwards!), goes off on tangents when he''s trying to talk someone into something, and generally miscommunicates most everything he says. He suffers a −1 penalty to Intimidation, Performance, Persuasion, and Taunt rolls that involve speech.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(37,'All Thumbs','minor',1,NULL,'core','Due to upbringing, lack of exposure, or pure bad luck, some individuals are "all thumbs" when it comes to mechanical or technological devices. All Thumbs inflicts a −2 penalty when using mechanical or electrical devices. If he rolls a Critical Failure while using such a device (and it doesn''t already have a built-in effect), it''s broken. If the GM feels it''s appropriate, it can be fixed with a Repair roll and 1d6 hours.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(38,'Anemic','minor',1,NULL,'core','Anemic characters are particularly susceptible to sickness, disease, environmental effects, and fatigue. They subtract 2 from Vigor rolls made to resist Fatigue.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(39,'Bad Eyes','minor',1,40,'core','Your hero''s eyes aren''t what they used to be. He suffers a −1 penalty to any Trait roll dependent on vision (such as ranged attacks and Notice rolls). In settings where glasses are available, they negate the penalty when worn. If lost or broken during a combat (generally a 50% chance when he''s Wounded, falls, or suffers some other trauma), the character is Distracted until the end of their next turn.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(40,'Bad Eyes','major',2,39,'core','Your hero''s eyes aren''t what they used to be. He suffers a −2 penalty to any Trait roll dependent on vision (such as ranged attacks and Notice rolls). In settings where glasses are available, they negate the penalty when worn. If lost or broken during a combat (generally a 50% chance when he''s Wounded, falls, or suffers some other trauma), the character is Distracted and Vulnerable until the end of their next turn.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(41,'Blind','major',2,NULL,'core','The individual is completely without sight. He suffers a −6 to all physical tasks that require vision (GM''s call). On the plus side, Blind characters gain their choice of a free Edge to compensate for this particularly difficult Hindrance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(42,'Can''t Swim','minor',1,NULL,'core','Most people in the 21st century can swim thanks to swimming pools, easy travel to lakes and beaches, or educational efforts. Historically, however, those who weren''t raised around a temperate body of water could not. Characters with this Hindrance suffer a −2 penalty to the Athletics skill when swimming and each inch moved in water costs 3″ of Pace.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(43,'Clumsy','major',2,NULL,'core','Your hero is an uncoordinated klutz who trips over air and is always the last one picked for sports. He subtracts 2 from Athletics and Stealth rolls.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(44,'Elderly','major',2,NULL,'core','Your adventurer is getting on in years, but he''s not quite ready for the nursing home yet. His Pace is reduced by 1, and he subtracts 1 from running rolls (minimum 1). He also suffers a −1 penalty to Agility, Strength (including damage), and Vigor rolls, but not linked skills. On the plus side, the wisdom of his years grants the hero 5 extra skill points which may be used for any skills linked to Smarts.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(45,'Hard of Hearing','minor',1,46,'core','Characters who have lost some of their hearing have this disadvantage. As a Minor Hindrance, it subtracts 4 from all Notice rolls made to hear, including awaking due to loud noises. Hearing aids reduce the penalty by 2, but require batteries and have a 50% chance of falling out when he''s Wounded, falls, or suffers some other trauma.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(46,'Hard of Hearing','major',2,45,'core','A Major Hindrance means the character is deaf. She cannot hear and automatically fails all Notice rolls that depend on hearing.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(47,'Mute','major',2,NULL,'core','Due to trauma or birth, your character has lost the ability to speak. He can write messages to others when needed, use sign language, or some combination of visual communication. Vision-based communication may require a Notice roll to perceive correctly (illumination and similar penalties apply).','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(48,'Obese','minor',1,NULL,'core','Those who carry their weight well have the Brawny Edge. Those who don''t are Obese. A character cannot be both Brawny and Obese, and this Hindrance can''t increase your Size above +3. An Obese hero''s Size (and therefore Toughness) increase by +1. His Pace is reduced by 1, and his running die one die type (minimum d4). Strength is considered one die type less (minimum d4) for armor and worn gear (not weapons). They may also have difficulty finding armor or clothing that fits or entering confined spaces.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(49,'One Arm','major',2,NULL,'core','By birth or battle, your hero has lost an arm. Fortunately, his other arm is (now) his "good" one. Tasks that require two hands, such as some Athletics rolls (GM''s call) or using a two-handed weapon, suffer a −4 modifier.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(50,'One Eye','major',2,NULL,'core','This veteran lost an eye and has trouble with depth perception. He subtracts 2 from any Trait roll dependent on vision and more than 5″ (10 yards) distant.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(51,'Slow','minor',1,52,'core','A disability or past injury has hindered this hero''s mobility. As a Minor Hindrance, reduce his Pace by 1 and his running die one step (if already d4, reduce to d4−1). Slow characters may not take the Fleet-Footed Edge. A character with the Minor version of this Hindrance may have a prosthesis. If the prosthesis is lost, he suffers the effects of the Major version of Slow.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(52,'Slow','major',2,51,'core','A disability or past injury has hindered this hero''s mobility. As a Major Hindrance, reduce the running die a step, Pace by 2, and subtract 2 from Athletics rolls and rolls to resist Athletics (such as Tests or Grappling). Slow characters may not take the Fleet-Footed Edge. From about the Victorian era forward, Slow heroes may start with a manual wheelchair at no cost. In the modern era (1980s and on), the character may also choose from an ultralight or powered chair.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(53,'Small','minor',1,NULL,'core','This adventurer is very skinny, very short, or both. His Size is reduced by 1, which reduces his Toughness as well. Size can''t be reduced below −1, but the Toughness penalty remains. A Small half-folk, for example, remains Size −1 and loses a point of Toughness.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(54,'Code of Honor','major',2,NULL,'core','Honor is very important to your character. He keeps his word, doesn''t abuse or kill prisoners, and generally tries to operate within his world''s particular notion of proper gentlemanly or ladylike behavior.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(55,'Death Wish','minor',1,NULL,'core','Having a death wish doesn''t mean your adventurer is suicidal—he might just think his life is worth less than some noble but clearly deadly goal. Those with a Death Wish don''t throw their lives away for no reason, but when there''s a chance to complete a goal they do anything—and take any risk—to achieve it.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(56,'Delusional','minor',1,57,'core','Your hero believes something that is considered quite strange by everyone else. Minor Delusions are harmless or the character generally keeps it to himself (the government puts sedatives in soft drinks, dogs can talk, we''re all just characters in some bizarre game, etc.).','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(57,'Delusional','major',2,56,'core','With a Major Delusion, he expresses his view on the situation frequently and it can occasionally lead to danger (the government is run by aliens, hospitals are deadly, I''m allergic to armor, zombies are my friends).','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(58,'Driven','minor',1,59,'core','A vow is a commitment to others. Driven characters want something for themselves. It may be to protect the realm, become a decorated officer, prove you''re the best gladiator in Rome, or the best pilot in the galactic fleet. The Minor version shapes the character and pushes his decisions but either happens rarely or is fairly harmless.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(59,'Driven','major',2,58,'core','As a Major Hindrance it''s an overriding desire that comes up frequently or causes peril for the heroine and those around her.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(60,'Hesitant','minor',1,NULL,'core','Your hero hesitates in stressful situations. Draw two Action Cards in combat and act on the lowest. If you draw a Joker, use it normally and ignore the Hindrance for the round (hence this being a Minor Hindrance, it actually increases your chances of drawing a Joker!)','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(61,'Phobia','minor',1,62,'core','Phobias are overwhelming and irrational fears that plague a hero''s psyche. Whenever a character is in the presence of his phobia (GM''s call, but generally sight), he subtracts 1 from all his Trait rolls if it''s a Minor Hindrance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(62,'Phobia','major',2,61,'core','Whenever a character is in the presence of his phobia (GM''s call, but generally sight), he subtracts 2 from all his Trait rolls if it''s a Major Hindrance. Phobias shouldn''t be too obvious; everyone should be afraid of vampires, for example, so it''s not a phobia, it''s common sense. Instead, the phobia usually centers on some random element the mind associates with the event. Remember, phobias are irrational fears.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(63,'Ruthless','minor',1,64,'core','The fanatic will do most anything to accomplish her goals. As a Minor Hindrance, she stops short of true harm to anyone except those who directly oppose her.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(64,'Ruthless','major',2,63,'core','As a Major Hindrance, she harms anyone and everyone who gets in her way.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(65,'Habit','minor',1,66,'core','Your warrior has an annoying or dangerous compulsion. A Minor Habit irritates those around her but isn''t dangerous. Maybe she picks her nose, can''t stop fiddling with her phone, says "y''know" in the middle of every sentence, or chews and smacks her gum loudly and often. Allies avoid her if possible.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(66,'Habit','major',2,65,'core','A Major Habit is a physical or mental addiction of some sort that is debilitating or possibly even deadly. This includes drug use, chronic drinking, or perhaps even an addiction to virtual reality in a high-tech setting. An addict who doesn''t get his fix must make a Vigor roll every 24 hours he goes without or take a level of Fatigue (see page 94). Once every 24 hours, a Healing roll with some sort of appropriate medicine removes one level of Fatigue for four hours. After that the Fatigue returns and can only be recovered with the addicting substance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(67,'Heroic','major',2,NULL,'core','This noble soul never says no to a person in need. She doesn''t have to be happy about it, but she always comes to the rescue of those she feels can''t help themselves. She''s the first one to run into a burning building, usually agrees to hunt monsters for little or no pay, and is generally a pushover for a sob story.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(68,'Jealous','minor',1,69,'core','Insecurity leads to envy of others'' accomplishments or being overly possessive of what this disgruntled soul feels belongs to him. He often complains, pouts, covets others'' possessions or accolades, claims credit for another''s work, disobeys commands, and generally causes problems. As a Minor Hindrance, the character''s jealousy is focused on one particular subject (such as his "unrivaled" skill as a pilot or a romantic interest).','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(69,'Jealous','major',2,68,'core','As a Major Hindrance, the character is jealous of anyone and everyone he feels outshines him. He consistently bad-mouths his rivals, tries to upstage them, or actively plots to discredit those who threaten his ego.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(70,'Loyal','minor',1,NULL,'core','This stalwart defender risks her life for her friends without hesitation. Some Loyal heroes may not act that way, but are the first to come to their friends'' rescue when they''re threatened.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(71,'Mean','minor',1,NULL,'core','This curmudgeon is ill-tempered and disagreeable. He has trouble doing anything kind for anyone else, must be paid for his troubles, and doesn''t accept awards or favors graciously. Besides the obvious roleplaying issues, Mean characters subtract 1 from Persuasion rolls.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(72,'Mild Mannered','minor',1,NULL,'core','Your milquetoast just isn''t threatening. Maybe he''s a little doughy around the middle, has a kind face, or a soft voice. Whatever the issue, he has a hard time looking tough. He subtracts 2 when making Intimidation rolls.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(73,'Outsider','minor',1,74,'core','In a society made up of only a few types of people, your hero isn''t one of them. A Native American in a Western town, an alien in a scifi game of human marines, or a half-orc in a party of elves, dwarves, and humans are all examples. Locals are likely to raise prices on her, ignore pleas for help, and generally treat her as lower class. Outsiders subtract 2 from Persuasion rolls made to influence those who aren''t her own kind.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(74,'Outsider','major',2,73,'core','The Major version also means the character has few or no legal rights in the main campaign area. She might be a different species among xenophobes, the civilization may be cruel and unenlightened toward strangers, or she might even be an artificial intelligence whose sapience isn''t acknowledged by the law.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(75,'Suspicious','minor',1,76,'core','Your character is suspicious of everyone. As a Minor Hindrance, his paranoia causes frequent trust issues. He might demand full payment before doing a task, want every agreement in writing, or believe even his friends are out to get him.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(76,'Suspicious','major',2,75,'core','As a Major Hindrance, Support rolls to aid the distrustful individual are made at −2.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(77,'Thin Skinned','minor',1,78,'core','Personal attacks really get under this individual''s skin. As a Minor Hindrance, he subtracts 2 when resisting Taunt attacks.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(78,'Thin Skinned','major',2,77,'core','As a Major, he subtracts 4.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(79,'Ugly','minor',1,80,'core','Attractive people get all the breaks. This unfortunate individual isn''t one of them. He subtracts 1 from his Persuasion rolls, or 2 if taken as a Major Hindrance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(80,'Ugly','major',2,79,'core','Attractive people get all the breaks. This unfortunate individual isn''t one of them. He subtracts 1 from his Persuasion rolls, or 2 if taken as a Major Hindrance.','2025-10-08 06:13:12','2025-10-08 06:13:12');
INSERT INTO hindrances VALUES(81,'Amorous','minor',1,NULL,'fantasy_companion','The character is easily enamored with a pretty face. Perhaps it''s lust or lechery, or perhaps he just has a keen appreciation of natural beauty. Amorous characters suffer an additional -2 penalty to resist Tests by any character with the Attractive or Very Attractive Edge.','2026-01-02 18:46:20','2026-01-02 18:46:20');
INSERT INTO hindrances VALUES(82,'Arcane Sensitivity','minor',1,83,'fantasy_companion','A spell gone wrong, an old curse, a strange bloodline, or some other mishap caused your hero to be more susceptible to arcane energy than others. Subtract 2 when making a Trait roll to resist a power, including arcane creature abilities (GM''s call).','2026-01-02 18:46:46','2026-01-02 18:46:46');
INSERT INTO hindrances VALUES(83,'Arcane Sensitivity','major',2,82,'fantasy_companion','A spell gone wrong, an old curse, a strange bloodline, or some other mishap caused your hero to be more susceptible to arcane energy than others. Subtract 4 when making a Trait roll to resist a power, including arcane creature abilities (GM''s call).','2026-01-02 18:46:46','2026-01-02 18:46:46');
INSERT INTO hindrances VALUES(84,'Armor Interference','minor',1,85,'fantasy_companion','This Hindrance may only be taken by those with an Arcane Background. Those with this Hindrance subtract 4 from arcane skill rolls, and cannot use other abilities granted by their Arcane Background Edge or any Edge that has Arcane Background as a Requirement when wearing medium or heavy armor, or using a medium or heavy shield. The character may wear cloth or light armor, or use light shields, without interference.','2026-01-02 18:47:03','2026-01-02 18:47:03');
INSERT INTO hindrances VALUES(85,'Armor Interference','major',2,84,'fantasy_companion','This Hindrance may only be taken by those with an Arcane Background. Those with this Hindrance subtract 4 from arcane skill rolls, and cannot use other abilities granted by their Arcane Background Edge or any Edge that has Arcane Background as a Requirement when wearing medium or heavy armor, or using a medium or heavy shield. As a Major Hindrance, the penalty also applies to light armor.','2026-01-02 18:47:03','2026-01-02 18:47:03');
INSERT INTO hindrances VALUES(86,'Blunderer','major',2,NULL,'fantasy_companion','Some heroes take a while to master their craft. Select a skill central to your character, such as Spellcasting for a wizard or Fighting for a warrior. The hero suffers a Critical Failure whenever she fails a roll and that skill die is a 1.','2026-01-02 18:47:24','2026-01-02 18:47:24');
INSERT INTO hindrances VALUES(87,'Corruption','major',2,NULL,'fantasy_companion','This Hindrance may only be taken by a character with an Arcane Background. The caster''s magic draws on some foul, evil, or tainted source. Whenever he rolls a Critical Failure on his arcane skill roll, he gains a new Minor Hindrance, or trades or upgrades a Minor Hindrance gained by Corruption for a Major Hindrance, that reflects his degrading mind and body. A wizard might become Jealous (Minor), for example, as he realizes how difficult it is to gather his power. Then Bloodthirsty (Major) as his rage turns to violent thoughts. These Hindrances last until the spelluser''s next Advance, at which time he may remove one Minor Hindrance, or reduce or trade a Major Hindrance for a Minor. This is in addition to his regular Advance.','2026-01-02 18:47:38','2026-01-02 18:47:38');
INSERT INTO hindrances VALUES(88,'Cursed','major',2,NULL,'fantasy_companion','Your heroine crossed some dark power and has forever after been marked by its tainted touch. Beneficial magical powers and effects intended to aid her, including those cast by allies or even herself, suffer a -2 penalty to the arcane skill roll. Worse, if the roll is a Critical Failure, the caster is Stunned! The penalty applies if the Cursed character is within an area effect power or targeted by the Additional Recipients modifier. The Curse has no effect on hostile powers.','2026-01-02 18:47:54','2026-01-02 18:47:54');
INSERT INTO hindrances VALUES(89,'Doomed','major',2,NULL,'fantasy_companion','Death is eager for your hero. Perhaps she cheated it at some point in her path, or was brought back from the dead and owes the Ferryman a fee. Whatever the reason, the heroine subtracts 2 from Soak rolls.','2026-01-02 18:48:08','2026-01-02 18:48:08');
INSERT INTO hindrances VALUES(90,'Grim','minor',1,NULL,'fantasy_companion','The hero is serious, taciturn, and finds mirth tiresome. He''s Provoked (see Savage Worlds) on any successful Taunt—whether the opponent has the Provoke Edge or not. Provoked characters subtract 2 from rolls to affect any opponent except the one who insulted him. This lasts until a Joker is drawn (by either side) or someone else successfully Taunts the dour ruffian.','2026-01-02 18:48:14','2026-01-02 18:48:14');
INSERT INTO hindrances VALUES(91,'Idealistic','minor',1,NULL,'fantasy_companion','You see things in black and white and struggle with more nuanced dilemmas. Most of the time this is an admirable virtue, but it causes great issues when on the horns of a moral dilemma, such as whether to hand a starving poacher over to the king''s guards or let him get away with his desperate but perhaps necessary crime.','2026-01-02 18:48:21','2026-01-02 18:48:21');
INSERT INTO hindrances VALUES(92,'Jingoistic','minor',1,93,'fantasy_companion','The character dislikes people from other cultures and believes his own to be far superior. He cannot help belittling other cultures at every opportunity. The targets of his ire may not benefit from his Command Edges. He subtracts 2 from Persuasion rolls when interacting with them.','2026-01-02 18:48:27','2026-01-02 18:48:27');
INSERT INTO hindrances VALUES(93,'Jingoistic','major',2,92,'fantasy_companion','The character dislikes people from other cultures and believes his own to be far superior. He cannot help belittling other cultures at every opportunity. The targets of his ire may not benefit from his Command Edges. He subtracts 4 from Persuasion rolls when interacting with them.','2026-01-02 18:48:27','2026-01-02 18:48:27');
INSERT INTO hindrances VALUES(94,'Material Components','major',2,NULL,'fantasy_companion','This Hindrance may only be taken by those with an Arcane Background. The spellcaster''s powers consume material items. Maybe a wizard needs a piece of brimstone to cast a fireball (blast with a fire Trapping) or a priestess needs a splash of holy water for her goddess to grant smite. Such items are assumed to be at hand—usually in a pocket, bag, or convenient pouch. If the caster is ever stripped of her possessions and can''t get the materials she needs, she reduces all arcane skill rolls by 4 until they''re restored (50gp x the caster''s Rank at a shop or a day''s worth of gathering or foraging in an appropriate environment with a Survival roll per Rank). A caster also runs out of material components if she rolls a Critical Failure and may replenish as above.','2026-01-02 18:48:33','2026-01-02 18:48:33');
INSERT INTO hindrances VALUES(95,'Selfless','minor',1,96,'fantasy_companion','You think of others before yourself. You sleep on the floor to give another the bed. You pretend to be full to give your friends the last bite of meat. You stand before your friends when the dragon breathes fire. You buy the book that everyone else in your adventuring party reads—a true hero! The extent and frequency of your sacrifice determines whether this is a Minor or Major Hindrance.','2026-01-02 18:48:39','2026-01-02 18:48:39');
INSERT INTO hindrances VALUES(96,'Selfless','major',2,95,'fantasy_companion','You think of others before yourself. You sleep on the floor to give another the bed. You pretend to be full to give your friends the last bite of meat. You stand before your friends when the dragon breathes fire. You buy the book that everyone else in your adventuring party reads—a true hero! The extent and frequency of your sacrifice determines whether this is a Minor or Major Hindrance.','2026-01-02 18:48:39','2026-01-02 18:48:39');
INSERT INTO hindrances VALUES(97,'Talisman','minor',1,98,'fantasy_companion','Only characters with an Arcane Background Edge can take this Hindrance. The caster is dependent on a physical item to activate his powers. The Talisman might be a magic staff, a sacred symbol, a wand, a weapon, or any other transportable item. When caught without it, he subtracts 1 from all arcane skill rolls, and is Stunned if the roll is a Critical Failure. Replacing a lost Talisman depends on the object, but should usually require getting it back from whoever took it. If it was destroyed, the Game Master should work with the player to figure out what might make a suitable replacement and how it might be gained.','2026-01-02 18:48:45','2026-01-02 18:48:45');
INSERT INTO hindrances VALUES(98,'Talisman','major',2,97,'fantasy_companion','Only characters with an Arcane Background Edge can take this Hindrance. The caster is dependent on a physical item to activate his powers. The Talisman might be a magic staff, a sacred symbol, a wand, a weapon, or any other transportable item. When caught without it, he subtracts 2 from all arcane skill rolls, and is Stunned if the roll is a Critical Failure. Replacing a lost Talisman depends on the object, but should usually require getting it back from whoever took it. If it was destroyed, the Game Master should work with the player to figure out what might make a suitable replacement and how it might be gained.','2026-01-02 18:48:45','2026-01-02 18:48:45');
COMMIT;
